name: common_github_search
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Harshvardhan Joshi <hj2931996@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  bloc: ^0.12.0
  equatable: ^0.2.0
  http: ^0.12.0

